name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Build
        run: |
          npm install
          npm run build
          tar -czvf docsfr.tar.gz docs
      - name: Release
        run: gh release create ${{ github.ref }} ./docsfr.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
